### PR TITLE
Upgrading lwip to 0.0.7 so that it will build with IOJS

### PR DESCRIPTION
**Pull request by blacha**
Support for IOJS was added in lwip 0.0.7 

https://github.com/EyalAr/lwip/pull/142

### CODE REVIEW

**Comment by Droogans** [comment]
May I ask how you're using this project? Is it working well for you?

I'm looking to start improving it in the coming weeks, any feedback would be appreciated. Feel free to respond here or by dropping issues into https://github.com/rackerlabs/snappit-mocha-protractor/issues.

**Comment by mikey0000** [comment]
@Droogans I was going to use it to take screenshots on build failures within a custom reporter. At the moment I realised protractor already has a screenshot utility so am going to attempt to use that for the time being. The number of build dependencies is a bit of a pain having to build every time on CI and the hoops I had to jump through just to build canvas(obviously not your fault).

**Comment by blacha** [comment]
@Droogans @mikey0000 works with me, I was not too sure where it was actually being used, so got him to respond :)

**Comment by Droogans** [comment]
@mikey0000 I'm currently struggling to install it myself, *even though I have it already installed in another directory*. It's crazy how fickle getting Canvas and Cairo is on a Mac.

I'll just point out that for the most part, I try to never have my team mates install this library locally, and [only have the CI server do it](https://github.com/rackerlabs/encore-ui/blob/605a648f4da1a1fbd527b77c4adaefc4cc75d482/utils/visual-regression/clone.sh#L4-L6). Getting this set up on Linux is so much easier.

I don't have an answer (or an idea, for that matter) on how to simplify installation.

**Comment by Droogans** [comment]
Ok I got it building again, there's an open issue where node-canvas isn't building on Mac OS...

After running through the changes in this PR, the output from running on lwip@0.0.6 and lwip@0.0.7 is identical. Thanks.

**Pull request merged**
