### PR TITLE
Update lwip to 0.0.9 to support Node6

### PR DESCRIPTION
**Pull request by jj4th**
Opening this on a primary branch.

### CODE REVIEW

**Comment by comeatmebro** [comment]
Test FAILed.

**Comment by Droogans** [comment]
These screenshots aren't working because of yet another "double click" issue with the dropdown menu.

At some point we'll need to sit down and make a demo site that isn't tied to angularjs.org, that way we can avoid these bizarre failures from blocking any tests here.

**Comment by Droogans** [comment]
You're going to need to [update the test commands running in codeship](https://app.codeship.com/projects/144712/configure_tests) to use node6.

The [.travis.yml file](https://github.com/rackerlabs/snappit-mocha-protractor/blob/a58e9012d14c15204e61cd1906bd7cccdf1f2d8f/.travis.yml#L5) also needs updated.

As does the [.node-version file](https://github.com/rackerlabs/snappit-mocha-protractor/blob/a58e9012d14c15204e61cd1906bd7cccdf1f2d8f/.node-version).

**Comment by comeatmebro** [comment]
Test FAILed.

**Comment by comeatmebro** [comment]
Test FAILed.

**Comment by Droogans** [comment]
Jenkins status updater is broken [this is the correct rebuild](https://jenkins.ui.encore.rackspace.com/job/PR%20Builder%20-%20visual-regression-tool/124/console) I kicked off manually...I guess it was still looking at a previous sha I force pushed over earlier this afternoon.

LGTM.

**Comment by jj4th** [comment]
So, who merges/releases this?

**Pull request merged**
